{
 "title": "計画保全進捗率",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "SiteName", "label": "拠点選択", "query": "茨城,北本,鳥取" },
   { "name": "top", "query": "5,10,20,30,50" },
   { "name": "ProcessName", "query": "Po5号ライン仕上,FI推進課" }
  ]
 },
 "panels": [
  {
   "title": "工場全体の計画保全進捗率 | Progress of the whole facatory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ライン別の進捗率 | Progress Rate by Line(s)",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  process_name AS 工程, \r\n  CAST(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished') THEN 1 ELSE 0 END) AS FLOAT\r\n  ) / COUNT(status) * 100 AS 完了率（％）\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '') and site_name = '${SiteName}'and $__timeFilter(due_date) \r\nGROUP BY\r\n  process_name\r\n"
    }
   ]
  },
  {
   "title": "年間進捗率（工程） | Annual Progress Rate by processes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  process_name AS \"設備 | Machines\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 1 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 1 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"1月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 2 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 2 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"2月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 3 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 3 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"3月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 4 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 4 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"4月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 5 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 5 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"5月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 6 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 6 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"6月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 7 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 7 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"7月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 8 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 8 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"8月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 9 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 9 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"9月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 10 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 10 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"10月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 11 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 11 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"11月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 12 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 12 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"12月\"\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  AND site_name = '${SiteName}' \r\n  AND EXTRACT(YEAR FROM due_date) = 2025  -- 例: 2025\r\nGROUP BY\r\n  process_name\r\nORDER BY\r\n  process_name;\r\n"
    }
   ]
  },
  {
   "title": "選択工程における計画保全進捗率 | Progress of the selected process ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "残件（今月） |  Remaining Cases of this month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1 ELSE 0 END) AS \"完了件数\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1 ELSE 0 END) AS \"未完了件数\"\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  AND site_name = '${SiteName}' \r\n  AND process_name = '${ProcessName}' \r\n  AND $__timeFilter(due_date)\r\n"
    }
   ]
  },
  {
   "title": "設備別の完了率 | Progress Ratio by machines",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  machine_name AS 設備, \r\n  CAST(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1 ELSE 0 END) AS FLOAT\r\n  ) / COUNT(status) * 100 AS  完了率（％）\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  and site_name = '${SiteName}' and process_name = '${ProcessName}' AND $__timeFilter(due_date)\r\nGROUP BY\r\n  machine_name\r\nORDER BY\r\n  machine_name ASC"
    }
   ]
  },
  {
   "title": "設備別の完了件数 | Progress Counts by machines",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  machine_name AS 設備,\r\n  SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1 ELSE 0 END) AS 完了件数,\r\n  SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1 ELSE 0 END) AS 未完了件数\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  AND site_name = '${SiteName}' \r\n  AND process_name = '${ProcessName}'\r\n  AND $__timeFilter(due_date)\r\nGROUP BY\r\n  machine_name\r\nORDER BY\r\n  machine_name ASC;"
    }
   ]
  },
  {
   "title": "年間進捗率（設備） | Annual Progress Rate by machines",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  machine_name AS \"設備 | Machines\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 1 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 1 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"1月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 2 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 2 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"2月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 3 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 3 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"3月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 4 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 4 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"4月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 5 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 5 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"5月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 6 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 6 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"6月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 7 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 7 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"7月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 8 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 8 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"8月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 9 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 9 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"9月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 10 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 10 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"10月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 11 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 11 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"11月\",\r\n  ROUND(\r\n    SUM(CASE WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 12 THEN 1 ELSE 0 END) * 100.0 /\r\n    NULLIF(SUM(CASE WHEN EXTRACT(MONTH FROM due_date) = 12 THEN 1 ELSE 0 END), 0), 2\r\n  ) AS \"12月\"\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  and site_name = '${SiteName}' \r\n  AND process_name = '${ProcessName}'\r\n  AND EXTRACT(YEAR FROM due_date) = 2025  -- 例: 2025\r\nGROUP BY\r\n  machine_name\r\nORDER BY\r\n  machine_name;\r\n"
    }
   ]
  },
  {
   "title": "担当者別の進捗件数 | Progress Counts by assginees",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  担当者,\r\n  SUM(完了フラグ) AS 完了件数,\r\n  SUM(未完了フラグ) AS 未完了件数\r\nFROM (\r\n  SELECT\r\n    CASE \r\n      WHEN assignees_display_name IS NULL OR assignees_display_name = '' THEN '未割付'\r\n      ELSE assignees_display_name\r\n    END AS 担当者,\r\n    CASE \r\n      WHEN status IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1\r\n      ELSE 0\r\n    END AS 完了フラグ,\r\n    CASE \r\n      WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') THEN 1\r\n      ELSE 0\r\n    END AS 未完了フラグ\r\n  FROM\r\n    scheduled_events\r\n  WHERE\r\n    NOT(machine_name = '')\r\n    AND site_name = '${SiteName}' \r\n    AND process_name = '${ProcessName}'\r\n    AND $__timeFilter(due_date)\r\n) AS sub\r\nGROUP BY\r\n  担当者\r\nORDER BY\r\n  CASE \r\n    WHEN 担当者 = '未割付' THEN 1\r\n    ELSE 0\r\n  END,\r\n  担当者;\r\n"
    }
   ]
  },
  { "title": "Beta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "残件（工程別） |  Remaining Cases by processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 1 THEN 1 ELSE 0 END) AS \"1月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 2 THEN 1 ELSE 0 END) AS \"2月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 3 THEN 1 ELSE 0 END) AS \"3月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 4 THEN 1 ELSE 0 END) AS \"4月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 5 THEN 1 ELSE 0 END) AS \"5月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 6 THEN 1 ELSE 0 END) AS \"6月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 7 THEN 1 ELSE 0 END) AS \"7月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 8 THEN 1 ELSE 0 END) AS \"8月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 9 THEN 1 ELSE 0 END) AS \"9月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 10 THEN 1 ELSE 0 END) AS \"10月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 11 THEN 1 ELSE 0 END) AS \"11月\",\r\n    SUM(CASE WHEN status NOT IN ('Finished', 'FinalApprovementFinished', 'Requesting') AND EXTRACT(MONTH FROM due_date) = 12 THEN 1 ELSE 0 END) AS \"12月\"\r\nFROM\r\n  scheduled_events\r\nWHERE\r\n  not(machine_name = '')\r\n  AND site_name = '${SiteName}' \r\n  AND process_name = '${ProcessName}' \r\n  AND EXTRACT(YEAR FROM due_date) = 2025  -- 例: 2025\r\n"
    }
   ]
  }
 ]
}